import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Sparkle Fountain",
    description: "A beautiful fountain of colorful sparks that lasts for 30 seconds.",
    price: 199,
    originalPrice: 249,
    discount: 20,
    image: "/placeholder.svg?height=300&width=300",
    inStock: true,
  },
  {
    id: "2",
    name: "Thunder Bomb",
    description: "Creates a loud bang with a flash of light. Perfect for celebrations.",
    price: 99,
    originalPrice: 129,
    discount: 23,
    image: "/placeholder.svg?height=300&width=300",
    inStock: true,
  },
  {
    id: "3",
    name: "Color Smoke Bombs",
    description: "Pack of 5 smoke bombs in different colors. Great for photography.",
    price: 299,
    originalPrice: 349,
    discount: 14,
    image: "/placeholder.svg?height=300&width=300",
    inStock: true,
  },
  {
    id: "4",
    name: "Rocket Launcher",
    description: "Shoots colorful rockets high into the sky with whistling sounds.",
    price: 499,
    originalPrice: 599,
    discount: 17,
    image: "/placeholder.svg?height=300&width=300",
    inStock: false,
  },
  {
    id: "5",
    name: "Sparklers Pack",
    description: "Pack of 20 sparklers that burn for 1 minute each. Safe for children.",
    price: 149,
    image: "/placeholder.svg?height=300&width=300",
    inStock: true,
  },
  {
    id: "6",
    name: "Festival Special Box",
    description: "A complete box with various crackers for the whole family.",
    price: 999,
    originalPrice: 1299,
    discount: 23,
    image: "/placeholder.svg?height=300&width=300",
    inStock: true,
  },
  {
    id: "7",
    name: "Ground Chakra",
    description: "Spins on the ground creating a circle of sparks. Pack of 10.",
    price: 199,
    image: "/placeholder.svg?height=300&width=300",
    inStock: true,
  },
  {
    id: "8",
    name: "Flower Pots",
    description: "Creates a fountain of colorful sparks. Pack of 5.",
    price: 349,
    originalPrice: 399,
    discount: 13,
    image: "/placeholder.svg?height=300&width=300",
    inStock: false,
  },
]
